language: objective-c
before_install:
  - brew update
  - brew install xctool --HEAD
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle install --path=vendor/bundle
  - bundle exec pod setup && bundle exec pod install
script: bundle exec rake test --trace

