language: objective-c
xcode_project: RHObjCExt.xcodeproj
xcode_scheme: RHObjCExt
before_install:
  - brew update
    #  - brew install xctool >/dev/null
  - gem update --system
  - gem install rake cocoapods
  - pod setup && pod install
script: bundle exec rake test --trace

